os: osx
addons:
  homebrew:
    packages:
    - libtool 
    - automake
    - autoconf
    - nasm
language: node_js
node_js:
  - 16
cache:
  npm: true
branches:
  only:
    - develop
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: develop
  local-dir: public
